version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:5001"
    command: tail -f /dev/null
    environment:
      - APP_NAME=auth-plus-notification
      - APP_PORT=5001
      - GO_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=./service-account-file.json
      - GOOGLE_APPLICATION_NAME=ifood2-63802
      - SENDGRID_URL=https://api.sendgrid.com/v3/mail/send
      - SENDGRID_API_KEY=asdwasdxcvr
      - MAILGUN_URL=https://api.mailgun.net/
      - MAILGUN_API_KEY=asdwasdxcvr
    volumes:
      - ./src:/app
    restart: always
    networks:
      - host
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.29.1
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - v-metrics:/prometheus
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    container_name: grafana
    image: grafana/grafana:8.1.2
    restart: always
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./docker/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  v-metrics: