version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:5001"
    command: tail -f /dev/null
    environment:
      - APP_NAME=auth-plus-notification
      - APP_PORT=5001
      - GO_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=./service-account-file.json
      - GOOGLE_APPLICATION_NAME=ifood2-63802
      - SENDGRID_URL=https://api.sendgrid.com/v3/mail/send
      - SENDGRID_API_KEY=asdwasdxcvr
    volumes:
      - ./src:/app
    restart: always
    networks:
      - host

networks:
  host:
    driver: bridge
