name: Continuous Delivery on Merge
on:
  push:
    branches: master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of golang
        uses: actions/setup-go@v2
        with:
          node-version: "^1.17.4"
      - name: Execute test
        run: make test/ci
